- name: Create toml for extra packages using template
  ansible.builtin.template:
    src: blueprint-extra-packages.toml.j2
    dest: "{{ blueprint_fragments_path }}/microshift-extras.toml"
    mode: '0644'
