- name: Enable gitops repo with rhsm_repository module
  community.general.rhsm_repository:
    name: "gitops-{{ gitops.version }}-for-rhel-{{ microshift.os_version.split('.')[0] }}-{{ microshift.arch }}-rpms"
    state: enabled

- name: Install microshift-gitops-release-info
  ansible.builtin.dnf:
    name: microshift-gitops-release-info
    state: present

- name: Read release-gitops.json from target host
  ansible.builtin.slurp:
    src: "/usr/share/microshift/release/release-gitops-{{ microshift.arch }}.json"
  register: gitops_release_info_json

- name: Set fact for release-gitops.json
  ansible.builtin.set_fact:
    gitops_release_info: "{{ gitops_release_info_json['content'] | b64decode | from_json }}"

- name: Create toml file from release-gitops.json using blueprint-from-release-info.toml.j2
  ansible.builtin.template:
    src: blueprint-from-release-info.toml.j2
    dest: "{{ blueprint_fragments_path}}/microshift-gitops.toml"
    mode: '0644'
  vars:
    package_name: microshift-gitops
    release_info: "{{ gitops_release_info }}"
