- name: Remove blueprint if exists
  ansible.builtin.file:
    path: /tmp/blueprint.toml
    state: absent

- name: Create tmp folder for fragments
  ansible.builtin.file:
    path: "{{ blueprint_fragments_path }}"
    state: directory
    mode: '0755'
    recurse: true
