- name: Enable rhocp repo with rhsm_repository module
  community.general.rhsm_repository:
    name: "rhocp-{{ microshift.version }}-for-rhel-{{ microshift.os_version.split('.')[0] }}-{{ microshift.arch }}-rpms"
    state: enabled

- name: Install microshift-release-info
  ansible.builtin.dnf:
    name: microshift-release-info
    state: present

- name: Add microshift.toml
  ansible.builtin.copy:
    src: "/usr/share/microshift/blueprint/blueprint-{{ microshift.arch }}.toml"
    dest: "{{ blueprint_fragments_path }}"
    mode: '0644'
    remote_src: true
