- name: Include osbuild_install.yml
  ansible.builtin.include_tasks: osbuild_install.yml

- name: Include osbuild_pull_secret.yml
  ansible.builtin.include_tasks: osbuild_pull_secret.yml

- name: Set fact for fragments directory
  ansible.builtin.set_fact:
    blueprint_fragments_path: /tmp/blueprints/fragments

- name: Include blueprint_empty.yml
  ansible.builtin.include_tasks: blueprint_create.yml

- name: Include gitops tasks if it is enabled
  when: gitops.enabled | bool
  block:
    - name: Include osbuild_gitops_sources.yml
      ansible.builtin.include_tasks: osbuild_gitops_sources.yml

    - name: Include blueprint_add_gitops.yml
      ansible.builtin.include_tasks: blueprint_add_gitops.yml

- name: Include multus tasks if it is enabled
  when: multus.enabled | bool
  block:
    # Add sources not needed, as it is in the same repo as microshift
    - name: Include blueprint_add_multus.yml
      ansible.builtin.include_tasks: blueprint_add_multus.yml

- name: Include blueprint_add_microshift.yml
  ansible.builtin.include_tasks: blueprint_add_microshift.yml

- name: Include blueprint_add_extras.yml
  ansible.builtin.include_tasks: blueprint_add_extras.yml

- name: Include blueprint_push.yml
  ansible.builtin.include_tasks: blueprint_push.yml
