# These tasks add the osbuild pull secret to the system
- name: Create /etc/osbuild-worker folder
  ansible.builtin.file:
    path: /etc/osbuild-worker
    state: directory
    mode: '0755'

- name: Copy content of pull_secret variable to /etc/osbuild-worker/containers-auth.json
  ansible.builtin.copy:
    content: "{{ pull_secret }}"
    dest: "/etc/osbuild-worker/containers-auth.json"
    mode: '0644'

- name: Copy osbuild-worker.toml
  ansible.builtin.copy:
    src: osbuild-worker.toml
    dest: /etc/osbuild-worker/osbuild-worker.toml
    mode: '0644'

- name: Restart osbuild-worker
  ansible.builtin.systemd:
    name: "osbuild-worker@1"
    state: restarted
