- name: Create VM disk from rhel9
  ansible.builtin.command: 
    cmd: >
      qemu-img create -f qcow2 -F qcow2 -b
        /var/lib/libvirt/images/{{ vm.builder.cloud_image }}
        /var/lib/libvirt/images/{{ vm.builder.name }}.img
        {{ vm.builder.disk_size }}
  args:
    creates: /var/lib/libvirt/images/{{ vm.builder.name }}.img

- name: Change permissions of VM disk
  ansible.builtin.file:
    path: /var/lib/libvirt/images/{{ vm.builder.name }}.img
    mode: '0664'

