- name: Enable rhocp repo with rhsm_repository module
  community.general.rhsm_repository:
    name: "rhocp-{{ microshift.version }}-for-rhel-{{ microshift.os_version.split('.')[0] }}-{{ microshift.arch }}-rpms"
    state: enabled

- name: Install microshift-release-info
  ansible.builtin.dnf:
    name: microshift-release-info
    state: present

- name: Enable gitops repo with rhsm_repository module
  community.general.rhsm_repository:
    name: "gitops-{{ gitops.version }}-for-rhel-{{ microshift.os_version.split('.')[0] }}-{{ microshift.arch }}-rpms"
    state: enabled

- name: Install microshift-gitops-release-info
  ansible.builtin.dnf:
    name: microshift-gitops-release-info
    state: present

- name: Read release-gitops.json from target host
  ansible.builtin.slurp:
    src: "/usr/share/microshift/release/release-gitops-{{ microshift.arch }}.json"
  register: gitops_release_info_json

- name: Set fact for release-gitops.json
  ansible.builtin.set_fact:
    gitops_release_info: "{{ gitops_release_info_json['content'] | b64decode | from_json }}"

- name: Create toml file from release-gitops.json using blueprint-from-release-info.toml.j2
  ansible.builtin.template:
    src: blueprint-from-release-info.toml.j2
    dest: /tmp/microshift-gitops.toml
    mode: '0644'

- name: Merge blueprint.toml and /tmp/blueprint.toml
  ansible.builtin.shell:
    cmd: "cat /usr/share/microshift/blueprint/blueprint-{{ microshift.arch }}.toml /tmp/microshift-gitops.toml > /tmp/merged-blueprint.toml"
    creates: /tmp/merged-blueprint.toml

- name: Push merged blueprint to osbuild
  ansible.builtin.command:
    cmd: "composer-cli blueprints push /tmp/merged-blueprint.toml"
