- name: Template gitops.toml into /tmp
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/tmp/{{ item | splitext | first }}"
    mode: '0644'
  loop:
    - gitops.toml.j2

- name: Add those sources to osbuild using composer-cli
  ansible.builtin.command:
    cmd: composer-cli sources add /tmp/{{ item }}
  loop:
    - gitops.toml
