- name: Install required packages
  ansible.builtin.dnf:
    name:
      - osbuild-composer
      - composer-cli
      - cockpit-composer
      - bash-completion
      - firewalld
    state: present

- name: Enable and start the builder services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - cockpit.socket
    - osbuild-composer.service
