- name: Send Microshift repo to fragments
  ansible.builtin.template:
    src: Containerfile.microshift-repo.j2
    dest: "{{ container_fragments.path }}/01-microshift-repo-Containerfile"
    mode: '0644'

- name: Enable rhocp repo with rhsm_repository module
  community.general.rhsm_repository:
    name: "rhocp-{{ microshift.version }}-for-rhel-{{ microshift.os_version.split('.')[0] }}-{{ microshift.arch }}-rpms"
    state: enabled

- name: Install microshift-release-info
  ansible.builtin.dnf:
    name: microshift-release-info
    state: present

- name: Read release.json from target host
  ansible.builtin.slurp:
    src: "/usr/share/microshift/release/release-{{ microshift.arch }}.json"
  register: microshift_release_info_json

- name: Set fact for release.json
  ansible.builtin.set_fact:
    microshift_release_info: "{{ microshift_release_info_json['content'] | b64decode | from_json }}"

- name: Send Microshift package to fragments
  ansible.builtin.template:
    src: Containerfile-from-release-info.j2
    dest: "{{ container_fragments.path }}/02-microshift-packages-Containerfile"
    mode: '0644'
  vars:
    package_name: microshift
    release_info: "{{ microshift_release_info }}"
